core/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('home.urls')),
]

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class CustomUser(AbstractUser):
    ROLES = (
        ('admin', 'Admin'),
        ('manager', 'Manager'),
        ('developer', 'Developer'),
        ('tester', 'Tester'),
    )

    role = models.CharField(max_length=20, choices=ROLES)


class Projects(models.Model):
    projects =  models.CharField(max_length=250,null=True,blank=True)

    def __str__(self):
        return self.projects

class Task(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('inprogress', 'In Progress'),
        ('testing', 'Testing'),
        ('completed', 'Completed'),
    )
    projects =  models.ForeignKey(Projects,null=True,blank=True,on_delete=models.CASCADE)
    description = models.TextField(null=True,blank=True)
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    assigned_to = models.ForeignKey(CustomUser,null=True,blank=True,on_delete=models.CASCADE,related_name='tasks_assigned_to')
    assigned_by = models.ForeignKey(CustomUser,null=True,blank=True,on_delete=models.CASCADE,related_name='tasks_assigned_by')

    def __str__(self):
        return self.name
 
    

templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Add Task</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

  <div class="container-fluid pt-2">
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand navbar-dark mx-3" href="{% url 'index' %}"><img src="{% static 'management.avif' %}" width="50" height="50" style=" border-radius: 60%;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto navbar-dark">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'add_project' %}">Add Project </a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#ffffff" height="20px" width="20px" version="1.1" id="Capa_1" viewBox="0 0 384.971 384.971" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"/><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"/><g id="SVGRepo_iconCarrier"> <g> <g id="Sign_Out"> <path d="M180.455,360.91H24.061V24.061h156.394c6.641,0,12.03-5.39,12.03-12.03s-5.39-12.03-12.03-12.03H12.03 C5.39,0.001,0,5.39,0,12.031V372.94c0,6.641,5.39,12.03,12.03,12.03h168.424c6.641,0,12.03-5.39,12.03-12.03 C192.485,366.299,187.095,360.91,180.455,360.91z"/> <path d="M381.481,184.088l-83.009-84.2c-4.704-4.752-12.319-4.74-17.011,0c-4.704,4.74-4.704,12.439,0,17.179l62.558,63.46H96.279 c-6.641,0-12.03,5.438-12.03,12.151c0,6.713,5.39,12.151,12.03,12.151h247.74l-62.558,63.46c-4.704,4.752-4.704,12.439,0,17.179 c4.704,4.752,12.319,4.752,17.011,0l82.997-84.2C386.113,196.588,386.161,188.756,381.481,184.088z"/> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </g> </g></svg> <strong>Logout</strong></a>
          </li>
        </ul>
        </div>
      </nav>
      <form class="myform" method="post" action="{% url 'add_task' %}" style="margin: 20px;">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_projects">Projects:</label>
          <select name="projects" class="form-select" required>
            <option selected>------</option>
            {% for project in projects %}
                <option value="{{ project.id }}">{{ project.projects }}</option>
            {% endfor %}
          </select>
      
          <label for="id_name">Name:</label>
          <input type="text" name="name" class="form-control" required>
      
          <label for="id_status">Status:</label>
          <select name="status" class="form-select">
            <option selected>------</option>
            <option value="pending">Pending</option>
            <option value="inprogress">In Progress</option>
            <option value="testing">Testing</option>
            <option value="completed">Completed</option>
          </select>
      
          <label for="id_assigned_to">Assigned To:</label>
          <select name="assigned_to" class="form-select" required>
            <option selected>------</option>
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
          </select>
      
          <label for="id_assigned_by">Assigned By:</label>
          <select name="assigned_by" class="form-select" required>
            <option selected>------</option>
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
          </select>
      
        </div>
        <button type="submit" class="btn btn-primary btn-block">Add Task</button>
    </form>
  </div>

    <!-- Bootstrap JS (Popper.js and Bootstrap JS) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    {% if error_message %}
    <div class="alert alert-success alert-dismissible d-flex align-items-center justify-content-center">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          {{ error_message }}
      </div>
    {% endif %}

    <div class="container-fluid custom-container d-flex justify-content-center my-5">
        <div class="row my-2 mx-2 main">
            <!--left-column-->
            <div class="col-md-6 col-12 mycol">
                <!--image-->
                <img src="{% static 'login.avif' %}" width="100%" height="100%">
            </div>
            <!--right-column-->
            <div class="col-md-6 col-12 xcol">
                <h2 class="title pt-5 pb-3">Sign In</h2>
                <form class="myform" method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="row rone">
                        <div class="form-group col-md-12 fone py-3">
                            <input type="text" name="username" id="username" class="form-control" placeholder="Username" required>
                        </div>
                    
                    </div>
                    <div class="row rtwo">
                        <div class="form-group col-md-12 fthree py-3">
                            <input type="password" name="password" id="password" class="form-control jk"  placeholder="Password" required>
                        </div>
                  
                    </div>
                    <div class="row rthree">
                        <div class="form-group col-md-8 ffive py-3">
                            <button type="submit" class="btn btn-primary btn-block"><span>Login</span></button>
                        </div>
    
                    </div>
                    <div class="row rfour">
                       
                        <div class="form-group col-md-12 feight py-3">
                            <p class="text-muted">Don't have an account?<br><a href="{% url 'register' %}">Register here</a></p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    

    <!-- Bootstrap JS (Popper.js and Bootstrap JS) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>

</html>

templates/projectform.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Add Project</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <div class="container-fluid pt-2">
      <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand navbar-dark mx-3" href="{% url 'index' %}"> <img src="{% static 'management.avif' %}" width="50" height="50" style=" border-radius: 60%;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto navbar-dark">
            {% comment %} <li class="nav-item">
              <a class="nav-link active" href="{% url 'add_task' %}">Add Task</a>
            </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#ffffff" height="20px" width="20px" version="1.1" id="Capa_1" viewBox="0 0 384.971 384.971" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"/><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"/><g id="SVGRepo_iconCarrier"> <g> <g id="Sign_Out"> <path d="M180.455,360.91H24.061V24.061h156.394c6.641,0,12.03-5.39,12.03-12.03s-5.39-12.03-12.03-12.03H12.03 C5.39,0.001,0,5.39,0,12.031V372.94c0,6.641,5.39,12.03,12.03,12.03h168.424c6.641,0,12.03-5.39,12.03-12.03 C192.485,366.299,187.095,360.91,180.455,360.91z"/> <path d="M381.481,184.088l-83.009-84.2c-4.704-4.752-12.319-4.74-17.011,0c-4.704,4.74-4.704,12.439,0,17.179l62.558,63.46H96.279 c-6.641,0-12.03,5.438-12.03,12.151c0,6.713,5.39,12.151,12.03,12.151h247.74l-62.558,63.46c-4.704,4.752-4.704,12.439,0,17.179 c4.704,4.752,12.319,4.752,17.011,0l82.997-84.2C386.113,196.588,386.161,188.756,381.481,184.088z"/> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </g> </g></svg> <strong>Logout</strong></a>
          </li>
        </ul>
        </div>
      </nav>
 
    <form class="myform" method="post" action="{% url 'add_project' %}" style="margin: 20px;">
      {% csrf_token %}
      <div class="form-group">
        <input type="text" name="project_name" class="form-control" placeholder="Project_Name" required >
      </div><br>
      <button type="submit" class="btn btn-primary btn-block">Add Project</button>

  </form>
</div>
    <!-- Bootstrap JS (Popper.js and Bootstrap JS) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>

</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% if error_message %}
    <div class="alert alert-success alert-dismissible d-flex align-items-center justify-content-center">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          {{ error_message }}
      </div>
    
{% endif %}
    <div class="container-fluid custom-container d-flex justify-content-center my-5">
        <div class="row my-2 mx-2 main">
            <!--left-column-->
            <div class="col-md-6 col-12 mycol">
                <!--image-->
                <img src="{% static 'register.avif' %}" width="100%" height="100%">
            </div>
            <!--right-column-->
            <div class="col-md-6 col-12 xcol">
                <h2 class="title pt-5 pb-3">Sign Up</h2>
                <form class="myform" method="post" action="{% url 'register' %}">
                    {% csrf_token %}
                    <div class="row rone">
                        <div class="form-group col-md-12 fone py-3">
                            <input type="text" name="username" id="username" class="form-control" placeholder="Username" required>
                        </div>
                    
                    </div>
                    <div class="row rtwo">
                        <div class="form-group col-md-12 fthree py-3">
                            <input type="password" name="password" id="password" class="form-control jk"  placeholder="Password" required>
                        </div>
                  
                    </div>
                    <div class="row rthree">
                        <div class="form-group col-md-8 ffive py-3">
                            <button type="submit" class="btn btn-primary btn-block"><span>Create account</span></button>
                        </div>
    
                    </div>
                    <div class="row rfour">
                       
                        <div class="form-group col-md-12 feight py-3">
                            <p class="text-muted">Already have an account?<br><a href="{% url 'login' %}">Sign in</a></p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS (Popper.js and Bootstrap JS) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>